{{- $HTTPS := .Values.proxy.https.enabled -}}
{{- $autoHTTPS := and $HTTPS (eq .Values.proxy.https.type "letsencrypt") .Values.proxy.https.hosts -}}
{{- if $autoHTTPS -}}
# This is solely used to provide auto HTTPS with our bundled kube-lego
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: jupyterhub-internal
  labels:
    {{- include "jupyterhub.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/ingress.provider: nginx
    kubernetes.io/ingress.class: jupyterhub-proxy-tls
    hub.jupyter.org/tls-terminator: "true"
spec:
  rules:
    {{- range $host := .Values.proxy.https.hosts }}
    - http:
        paths:
          - path: /
            backend:
              serviceName: proxy-http
              servicePort: 8000
      host: {{ $host }}
    {{- end }}
  tls:
    - secretName: kubelego-tls-proxy-{{ .Release.Name }}
      hosts:
        {{- .Values.proxy.https.hosts | toYaml | trimSuffix "\n" | nindent 8 }}
{{- end }}
