# dependabot.yml reference: https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/configuration-options-for-dependency-updates
#
version: 2
updates:
  # Maintain Python dependencies for the jupyterhub/k8s-hub image
  - package-ecosystem: pip
    directory: "/images/hub"
    schedule:
      interval: daily
      time: "00:00"
      timezone: "Etc/UTC"
    versioning-strategy: lockfile-only
    labels:
      - maintenance
      - dependencies

  # Maintain Python dependencies for the jupyterhub/k8s-singleuser-sample image
  - package-ecosystem: pip
    directory: "/images/singleuser-sample"
    schedule:
      interval: daily
      time: "05:00"
      timezone: "Etc/UTC"
    versioning-strategy: lockfile-only
    labels:
      - maintenance
      - dependencies

  # Maintain dependencies in our GitHub Workflows
  - package-ecosystem: "github-actions"
    directory: "/"  # This should be / rather than .github/workflows
    schedule:
      interval: daily
      time: "05:00"
      timezone: "Etc/UTC"
    labels:
      - maintenance
      - dependencies
