# pre-commit is a tool to perform a predefined set of tasks manually and/or
# automatically before git commits are made.
#
# Config reference: https://pre-commit.com/#pre-commit-configyaml---top-level
#
# Common tasks
#
# - Run on all files:   pre-commit run --all-files
# - Register git hooks: pre-commit install --install-hooks
#
# About bash scripts autoformatting
#
# All hooks in this file can automatically be installed by pre-commit, but the
# hook we want to use for bash script formatting, shellcheck, must be manually
# installed. If needed, install it and run it using the link and snippet below.
#
#   https://github.com/koalaman/shellcheck#installing
#
#   pre-commit run --config .pre-commit-config-shellcheck.yaml --all-files
#
repos:
  # Autoformat: Python code
  - repo: https://github.com/psf/black
    rev: 21.7b0
    hooks:
      - id: black
        args: [--target-version=py36]

  # Autoformat: Bash scripts
  - repo: https://github.com/lovesegfault/beautysh
    rev: v6.1.0
    hooks:
      - id: beautysh

  # Autoformat: markdown, yaml (but not helm templates)
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.3.2
    hooks:
      - id: prettier

  # Reset Chart.yaml version and values.yaml image tags
  - repo: https://github.com/jupyterhub/chartpress
    rev: 1.2.2
    hooks:
      - id: chartpress
