# pre-commit is a tool to perform a predefined set of tasks manually and/or
# automatically before git commits are made.
#
# Config reference: https://pre-commit.com/#pre-commit-configyaml---top-level
#
# Common tasks
#
# - Run on all files:   pre-commit run --all-files
# - Register git hooks: pre-commit install --install-hooks
#
# About bash scripts autoformatting
#
# All hooks in this file can automatically be installed by pre-commit, but the
# hook we want to use for bash script formatting, shellcheck, must be manually
# installed. If needed, install it and run it using the link and snippet below.
#
#   https://github.com/koalaman/shellcheck#installing
#
#   pre-commit run --hook-stage=manual shellcheck --all-files
#
repos:
  # Autoformat: Python code, syntax patterns are modernized
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.15.0
    hooks:
      - id: pyupgrade
        args:
          - --py38-plus

  # Autoformat: Python code
  - repo: https://github.com/psf/black
    rev: 23.10.1
    hooks:
      - id: black
        args:
          - --target-version=py38
          - --target-version=py39
          - --target-version=py310
          - --target-version=py311
          - --target-version=py312

  # Autoformat: Python code
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args:
          - --profile=black

  # Autoformat: Bash scripts
  - repo: https://github.com/lovesegfault/beautysh
    rev: v6.2.1
    hooks:
      - id: beautysh

  # Autoformat: markdown, yaml (but not helm templates)
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.3
    hooks:
      - id: prettier

  # Reset Chart.yaml version and values.yaml image tags
  - repo: https://github.com/jupyterhub/chartpress
    rev: 2.1.0
    hooks:
      - id: chartpress

  # Linting: Python code (see the file .flake8)
  - repo: https://github.com/PyCQA/flake8
    rev: "6.1.0"
    hooks:
      - id: flake8

  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.22
    hooks:
      # This requires shellcheck to be installed manually so is disabled by default
      - id: shellcheck
        stages:
          - manual

# pre-commit.ci config reference: https://pre-commit.ci/#configuration
ci:
  autoupdate_schedule: monthly
