dist: bionic
language: python
python:
  - 3.6
git:
  ## depth set to false overrides travis default behavior to use shallow clones
  ## with depth 50 that can cause issues
  ##
  ## ref: https://github.com/jupyterhub/chartpress#shallow-clones
  ##
  depth: false
services:
  - docker
## stages declares and orders stages
##
## ref: https://docs.travis-ci.com/user/build-stages/#build-stages-and-deployments
##
stages:
  - name: lint and validate
  - name: test
  - name: publish
    if: >
      branch in (master)
      AND
      type in (push)
install:
  - set -e
  - pip3 install --no-cache-dir -r dev-requirements.txt
  - . ci/common

stage: test
script:
  - setup_kubectl
  - setup_kind
  - setup_helm
  - ./ci/travis-docker-fix
  - ./dev kind create
  - helm repo add jupyterhub https://jupyterhub.github.io/helm-chart/
  - helm repo update
  - ./dev upgrade --chart jupyterhub/jupyterhub --version 0.8.2
  - ./dev upgrade --chart ./jupyterhub
  - ./dev port-forward
  - ./dev test
env:
  ## NOTE: The environment variables will be expanded to multiple jobs. For
  ##       additional individual jobs, only the first entry is used.
  ##
  ## ref: https://docs.travis-ci.com/user/build-stages/#build-stages-and-build-matrix-expansion
  ##
  ##
  ## Z2JH_KUBE_VERSION should match a released kindest/node image tag, but they
  ## are currently not automatically published.
  ##
  ## ref: https://hub.docker.com/r/kindest/node/tags
  ## ref: https://github.com/kubernetes-sigs/kind/issues/197
  ##
  - Z2JH_KUBE_VERSION=1.15.3
  - Z2JH_KUBE_VERSION=1.13.10
  - &allow_failure Z2JH_KUBE_VERSION=1.16.2

jobs:
  ## allow experimental setups to fail
  ##
  ## ref: https://docs.travis-ci.com/user/customizing-the-build/#rows-that-are-allowed-to-fail
  ##
  allow_failures:
    - env: *allow_failure
  ## don't wait for the jobs that are allowed to fail to report success
  ##
  ## ref: https://docs.travis-ci.com/user/customizing-the-build/#fast-finishing
  ##
  fast_finish: true

  ## include additional individual jobs
  ##
  include:
    - stage: lint and validate
      script:
        - setup_helm
        - setup_kubeval
        - ./dev check templates
      env:
        - Z2JH_VALIDATE_KUBE_VERSIONS=1.11.0,1.12.0,1.13.0,1.14.0,1.15.0,1.16.0
    - stage: publish
      script:
        - setup_git_crypt
        - setup_helm
        - helm init --client-only
        - ./ci/travis-docker-fix
        - ./ci/publish
      env:
        ## encrypted environment variables, used on push to master in the
        ## publish script to in turn decrypt a SSH key
        ##
        ## ref: https://docs.travis-ci.com/user/environment-variables/#encrypting-environment-variables
        - secure: jpFpbMccpjGP+otWH2Z03VFdtR9AAu2vzrNxsoZ3IvJvrO4MfzYJ3uSCDQuB0NG9gBgaAscpTJtliPTEi7njXHLcsFeWXLUmeBEHLozYxfzDQzMvW3EYdNWcC7oVAAt3de0i0ojw9rGswiofhbu2dAe+Xd2bejv1+PVJcEC3SRPGy17kb6bme6gD3zty5ft4VpzP0nomUNqfZBRLUYxSZuKlHJaZ6Nuq434rKmXrcN6uy+eEWDorTbjyM22IIYgUmrhg++Qtu/MBR7/rriPhyRltCU14361bcxqyq2Hw+HNG8D3hsqo5TiEiYwxOQcXRgddL+Ci6/y0L1EvqOQc+1V8ycwNs2oNicwNgSn5A+9HpF495Kae039hGtj2Gpt4IbplSYwKFq/sFTq+CekxdD2YVQmGvsjep4bNVL66o2RSZVAW1Bg/G8/sSe3BwgD8IToy9+1NHPPuaVupeukRqNyUDcVvWH8hdb8AkXYY87+546etYDpn91GQnhTEberKbXX4UCmpKNXpXoprLE8nQLGb6TIoHPTyA+RRNQ4erDzMjqF43UVmhOZTtkGaRgIWK7vDAKpLUnuOguuhJUNpYpRggGQsMV8cZnaCumy5OFUf6i6rfN0Ru6a+/Bm7grJiAcnZlU7igaxgI38QaJgCKcqqzIImdcRYNQC74/Ok/1oM=
        - secure: BK++GwKVPoS0iG8aB7wQ13daTgJR9MifHA+l9xr/tSZ3SUL6nc7kjxLbliRQJCqT9lcOODsd+v2u9PziEzBp0CCh67ftFxJw8riP2+FgdmHTK4yav9QpSwoBJHhV2SgBMGlXiqdUVC7wpgjzzK63V8abvzAhXkthWPl3kYpUI//xGYyuBNXVHEOImHB3F1M5bn90lflFtRfq2iH5FigGesMi2BFfTVeqvbzZVZrAs0E1/NRdO+/cRq0c9aRpNLkh254k1tcKbUvULQq1iLQuHN2Ramn3NgNnx93sbwp1e7ZjmETbjr9cwMIDg5mh25H0Rjf2Nn8cqHbBCWzoMkjZW097HRVDYht2kJZQIbQcaxX38DW6vykUwGWSBAWbtvCUwYwU57s/dIbSYUTQErkYYmhiq52cdOtnxZ2/ULoElCVyR8lTmQuANJrq9YFC9q1ly69YuMWWnFgwxWpK1JCgAJGELgj5EvcghEtNmkEFh5f6pmbKBE7PKQPTovzNKcdRauR/L+MsmhVYukCfNZq57LrruIQIX1GQNw9w3Ck8P4EPtNjdI4umCSy6nZSyTevWgVTmIP9EwXa5Cap32ZU+iDtw+wUBAr3sjROJOYGKlL/ktWsWbjog5hIG0rrb8PbgOfbLRZSEYGL9sYsyXXyW5oI37lB7AqG6D7vOA4TdmTQ=
