proxy:
  secretToken: pppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppp
  service:
    type: NodePort
    nodePorts:
      http: 30080
      https: 30443
  https:
    enabled: true
    type: letsencrypt
    hosts:
      - local.jovyan.org
    letsencrypt:
      contactEmail: 'jovyan@jupyter.test'
      acmeServer: https://pebble/dir
  traefik:
    extraVolumes:
      - name: pebble-root-cert
        configMap:
          name: pebble
    extraVolumeMounts:
      - name: pebble-root-cert
        subPath: root-cert.pem
        mountPath: /etc/pebble/root-cert.pem
    extraEnv:
      LEGO_CA_CERTIFICATES: /etc/pebble/root-cert.pem
  chp:
    resources:
      requests:
        memory: 0
        cpu: 0
    networkPolicy:
      egress: []  # overrides allowance of 0.0.0.0/0

hub:
  cookieSecret: cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
  db:
    type: sqlite-memory
  services:
    test:
      admin: true
      apiToken: ssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss
  networkPolicy:
    egress:  # overrides allowance of 0.0.0.0/0
      # In kind/k3s clusters the Kubernetes API server is exposing this port
      - ports:
        - protocol: TCP
          port: 6443
  resources:
    requests:
      memory: 0
      cpu: 0

singleuser:
  storage:
    type: none
  memory:
    guarantee: null
  networkPolicy:
    # For testing purposes in test_singleuser_netpol
    egress:
      - to:
        # jupyter.org has multiple IPs associated with it, among them are these
        # two. We explicitly allow access to one, but leave out the the other.
        - ipBlock:
            cidr: 104.28.8.110/32
        # - ipBlock:
        #     cidr: 104.28.9.110/32
  extraEnv:
    TEST_ENV_FIELDREF_TO_NAMESPACE:
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace

prePuller:
  hook:
    enabled: false

scheduling:
  userScheduler:
    enabled: true
    replicas: 2
    logLevel: 10

debug:
  enabled: true
