apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hub
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: hub
        app: jupyterhub
        component: hub
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
        {{ if .Values.hub.labels -}}
        # Because toYaml + indent is super flaky
        {{ range $key, $value := .Values.proxy.labels -}}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
        {{- end }}
    spec:
      nodeSelector: {{ toJson .Values.hub.nodeSelector }}
      volumes:
      - name: config
        configMap:
          name: hub-config
      - name: secret
        secret:
          secretName: hub-secret
      {{ if eq .Values.hub.db.type "sqlite-pvc" }}
      - name: hub-db-dir
        persistentVolumeClaim:
          claimName: hub-db-dir
      {{- end }}
      {{- if .Values.rbac.enabled }}
      serviceAccountName: hub
      {{- end }}
      securityContext:
        runAsUser: {{ .Values.hub.uid }}
        fsGroup: {{ .Values.hub.fsGid }}
      containers:
      {{- if .Values.hub.extraContainers }}
{{ toYaml .Values.hub.extraContainers | indent 6 }}
      {{ end }}
      - name: hub-container
        image: {{ .Values.hub.image.name }}:{{ .Values.hub.image.tag }}
        command:
          - watchmedo
          - auto-restart
          - --directory
          - /etc/jupyterhub/config/
          - --directory
          - /etc/jupyterhub/secret/
          - --interval
          - "5"
          - --ignore-directories
          - --ignore-pattern
          - '.*'
          - --
          - jupyterhub
          - --config
          - /srv/jupyterhub_config.py
          # We want to do automatic upgrades for sqlite-pvc by default, but allow users
          # to opt out of that if they want. Users using their own db need to 'opt in'
          # Go Templates treat nil and "" and false as 'false', making this code complex.
          # We can probably make this a one-liner, but doing combinations of boolean vars
          # in go templates is very inelegant & hard to reason about.
          {{- $upgradeType := typeOf .Values.hub.db.upgrade }}
          {{- if eq $upgradeType "bool" }}
          # .Values.hub.db.upgrade has been explicitly set to true or false
          {{- if .Values.hub.db.upgrade }}
          - --upgrade-db
          {{- end }}
          {{- else if eq $upgradeType "<nil>" }}
          # .Values.hub.db.upgrade is nil
          {{- if eq .Values.hub.db.type "sqlite-pvc" }}
          - --upgrade-db
          {{- end }}
          {{- end }}
        volumeMounts:
          - mountPath: /etc/jupyterhub/config/
            name: config
          - mountPath: /etc/jupyterhub/secret/
            name: secret
        {{ if eq .Values.hub.db.type "sqlite-pvc" }}
          - mountPath: /srv/jupyterhub
            name: hub-db-dir
            {{ if .Values.hub.db.pvc.subPath -}}
            subPath: {{ .Values.hub.db.pvc.subPath | quote }}
            {{- end }}
        {{- end }}
        resources:
{{ toYaml .Values.hub.resources | indent 12}}
        imagePullPolicy: {{ .Values.hub.imagePullPolicy }}
        env:
        # Put this here directly so hub will restart when we
        # change this
        - name: SINGLEUSER_IMAGE
          value:  "{{ .Values.singleuser.image.name }}:{{ .Values.singleuser.image.tag }}"
        {{ if .Values.hub.cookieSecret }}
        - name: JPY_COOKIE_SECRET
          valueFrom:
            secretKeyRef:
              name: hub-secret
              key: hub.cookie-secret
        {{- end }}
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: CONFIGPROXY_AUTH_TOKEN
          valueFrom:
            secretKeyRef:
              name: hub-secret
              key: proxy.token
        {{ range $key, $value := .Values.hub.extraEnv -}}
        - name: {{ $key | quote }}
          value: {{ $value | quote }}
        {{ end -}}
        ports:
          - containerPort: 8081
            name: hub
