#
# We are using a GCE disk as persistent storage for the Hub
# and for each individual user node.
#
# A volume for the hub is automatically provisioned b/c its pvc
# is using a storage class. There is no need to manually provision
# any disks on the cluster.
#
# When a single user pod is spun up, a corresponding pvc is
# dynamically provisioned by kubespawner. If a pvc for that user
# already exists, the pod mounts to the existing pvc.
#

kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
  name: gce-standard-storage
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-standard
  zone: us-central1-a
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: data8-workdir
  annotations:
    volume.beta.kubernetes.io/storage-class: gce-standard-storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: proxy-api
spec:
  selector:
    name: proxy-pod
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
---
apiVersion: v1
kind: Service
metadata:
  name: proxy-public
spec:
  type: LoadBalancer
  selector:
    name: proxy-pod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: hub
spec:
  selector:
    name: hub-pod
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hub-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: hub-pod
    spec:
      volumes:
      - name: data8-workdir-volume
        persistentVolumeClaim:
          claimName: data8-workdir
      containers:
      - name: hub-container
        image: data8/jupyterhub-k8s-hub:master
        imagePullPolicy: Always
        volumeMounts:
          - mountPath: /srv/jupyterhub
            name: data8-workdir-volume
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: CULL_JHUB_TOKEN
          valueFrom:
            configMapKeyRef:
              name: hub-config
              key: auth.jhub-token.cull
        - name: CONFIGPROXY_AUTH_TOKEN
          valueFrom:
            configMapKeyRef:
              name: hub-config
              key: auth.jhub-token.proxy
        - name: GOOGLE_OAUTH_CLIENT_ID
          valueFrom:
            configMapKeyRef:
              name: hub-config
              key: oauth.client-id.google
        - name: GOOGLE_OAUTH_CLIENT_SECRET
          valueFrom:
            configMapKeyRef:
              name: hub-config
              key: oauth.client-secret.google
        - name: OAUTH_CALLBACK_URL
          value: "{{ .Values.oauthCallbackUrl }}"
        ports:
          - containerPort: 8081
            name: hub
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: proxy-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: proxy-pod
    spec:
      containers:
      - name: proxy-container
        image: yuvipanda/nchp:v1
        env:
          - name: CONFIGPROXY_AUTH_TOKEN
            valueFrom:
              configMapKeyRef:
                name: hub-config
                key: auth.jhub-token.proxy
        ports:
          - containerPort: 8000
            name: proxy-public
          - containerPort: 8001
            name: api

