{{ if and .Values.cull.enabled .Values.cull.maxAge }}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: pod-culler
  labels:
    app: jupyterhub
    component: pod-culler
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  template:
    metadata:
      labels:
        app: jupyterhub
        component: pod-culler
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
    spec:
      {{ if .Values.rbac.enabled }}
      {{- if eq .Values.rbac.customServiceAccount "" }}
      serviceAccountName: pod-culler
      {{ else }}
      serviceAccountName: {{ .Values.rbac.customServiceAccount }}
      {{- end }}
      {{- end }}
      containers:
        - name: culler
          image: {{ .Values.cull.podCuller.image.name }}:{{ .Values.cull.podCuller.image.tag }}
          resources:
            requests:
              memory: 100Mi
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: LABEL_SELECTOR
              value: "component=singleuser-server"
            - name: MAX_AGE
              value: {{ .Values.cull.maxAge | quote }}
            - name: CULL_INTERVAL
              value: {{ .Values.cull.every | quote }}
{{ end }}
