{{ $manualHTTPS := (and .Values.proxy.https.enabled (eq .Values.proxy.https.type "manual" ) ) }}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: proxy
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: proxy
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        # This lets us autorestart when the secret changes!
        checksum/hub-secret: {{ include (print $.Template.BasePath "/hub/secret.yaml") . | sha256sum }}
        checksum/proxy-secret: {{ include (print $.Template.BasePath "/proxy/secret.yaml") . | sha256sum }}
      labels:
        name: proxy
        component: proxy
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
        hub.jupyter.org/network-access-hub: "true"
        hub.jupyter.org/network-access-singleuser: "true"
    spec:
      nodeSelector: {{ toJson .Values.proxy.nodeSelector }}
      affinity:
        podAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              podAffinityTerm:
                topologyKey: kubernetes.io/hostname
                labelSelector:
                  matchExpressions:
                    - key: component
                      operator: In
                      values: ['hub']
                    - key: release
                      operator: In
                      values: [ {{ .Release.Name | quote }} ]
      {{ if $manualHTTPS }}
      volumes:
      - name: tls-secret
        secret:
          secretName: manual-tls-proxy-{{ .Release.Name }}
      {{ end }}
      containers:
        - name: chp
          image: {{ .Values.proxy.chp.image.name }}:{{ .Values.proxy.chp.image.tag }}
          command:
          - configurable-http-proxy
          - --ip=0.0.0.0
          - --api-ip=0.0.0.0
          - --api-port=8001
          - --default-target=http://$(HUB_SERVICE_HOST):$(HUB_SERVICE_PORT)
          - --error-target=http://$(HUB_SERVICE_HOST):$(HUB_SERVICE_PORT)/hub/error
          {{ if $manualHTTPS }}
          - --port=8443
          - --redirect-port=8000
          - --ssl-key=/etc/chp/tls/tls.key
          - --ssl-cert=/etc/chp/tls/tls.crt
          {{ else }}
          - --port=8000
          {{ end }}
          {{ if .Values.debug.enabled }}
          - --log-level debug
          {{ end }}
          resources:
          {{ if $manualHTTPS }}
          volumeMounts:
          - name: tls-secret
            mountPath: /etc/chp/tls
            readOnly: true
          {{ end }}
{{ toYaml .Values.proxy.chp.resources | indent 12 }}
          env:
            - name: CONFIGPROXY_AUTH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: hub-secret
                  key: proxy.token
          imagePullPolicy: {{ .Values.proxy.chp.image.pullPolicy }}
          ports:
            {{ if $manualHTTPS }}
            - containerPort: 8443
              name: proxy-https
            {{ end }}
            - containerPort: 8000
              name: proxy-public
            - containerPort: 8001
              name: api
      terminationGracePeriodSeconds: 60
