{{- if .Values.scheduling.userScheduler.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-scheduler
  labels:
    {{- include "jupyterhub.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.scheduling.userScheduler.replicas }}
  selector:
    matchLabels:
      {{- include "jupyterhub.matchLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "jupyterhub.matchLabels" . | nindent 8 }}
      annotations:
        checksum/config-map: {{ include (print $.Template.BasePath "/scheduling/user-scheduler/configmap.yaml") . | sha256sum }}
    spec:
      {{- if .Values.rbac.enabled }}
      serviceAccountName: user-scheduler
      {{- end }}
      {{- if .Values.scheduling.podPriority.enabled }}
      priorityClassName: {{ .Release.Name }}-default-priority
      {{- end }}
      nodeSelector: {{ toJson .Values.scheduling.userScheduler.nodeSelector }}
      tolerations: {{ toJson .Values.scheduling.userScheduler.tolerations }}
      {{- include "jupyterhub.coreAffinity" . | nindent 6 }}
      volumes:
        - name: config
          configMap:
            name: user-scheduler
      {{- with include "jupyterhub.imagePullSecrets" (dict "root" . "image" .Values.scheduling.userScheduler.image) }}
      imagePullSecrets: {{ . }}
      {{- end }}
      containers:
        - name: user-scheduler
          # NOTE: When the kube-scheduler 1.17+ binaries fail to find CSINode
          #       resource in the cluster, they won't start scheduling. Due to
          #       this, we fallback to the latest functional version with its
          #       legacy configuration format. This fallback can be removed when
          #       we assume k8s 1.17 where CSINode is generally available.
          {{- if .Capabilities.APIVersions.Has "storage.k8s.io/v1/CSINode" }}
          image: {{ .Values.scheduling.userScheduler.image.name }}:{{ .Values.scheduling.userScheduler.image.tag }}
          {{- else }}
          image: {{ .Values.scheduling.userScheduler.image.name }}:v1.16.15
          {{- end }}
          {{- with .Values.scheduling.userScheduler.image.pullPolicy }}
          imagePullPolicy: {{ . }}
          {{- end }}
          command:
            - /usr/local/bin/kube-scheduler
            # NOTE: --leader-elect-... (new) and --lock-object-... (deprecated)
            #       flags are silently ignored in favor of whats defined in the
            #       passed KubeSchedulerConfiguration whenever --config is
            #       passed.
            #
            # ref: https://kubernetes.io/docs/reference/command-line-tools-reference/kube-scheduler/
            #
            # NOTE: --authentication-skip-lookup=true is used to avoid a
            #       seemingly harmless error, if we need to not skip
            #       "authentication lookup" in the future, see the linked issue.
            #
            # ref: https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/1894
            {{- if .Capabilities.APIVersions.Has "storage.k8s.io/v1/CSINode" }}
            - --config=/etc/user-scheduler/config.yaml
            - --authentication-skip-lookup=true
            {{- else }}
            - --scheduler-name={{ .Release.Name }}-user-scheduler
            - --policy-config-file=/etc/user-scheduler/policy.cfg
            - --lock-object-name=user-scheduler-lock
            - --lock-object-namespace={{ .Release.Namespace }}
            {{- end }}
            - --v={{ .Values.scheduling.userScheduler.logLevel | default 4 }}
          volumeMounts:
            - mountPath: /etc/user-scheduler
              name: config
          livenessProbe:
            httpGet:
              path: /healthz
              port: 10251
            initialDelaySeconds: 15
          readinessProbe:
            httpGet:
              path: /healthz
              port: 10251
          resources:
            {{- .Values.scheduling.userScheduler.resources | toYaml | trimSuffix "\n" | nindent 12 }}
          {{- with .Values.scheduling.userScheduler.containerSecurityContext }}
          securityContext:
            {{- . | toYaml | trimSuffix "\n" | nindent 12 }}
          {{- end }}
{{- end }}
